#!/bin/sh

if [[ ! $(acpi) ]]; then
    echo "NO ACPI"
    echo "NO ACPI"
    echo ""
    exit 0
fi


if [[ $(acpi | grep "information unavailable" ) ]]; then
    echo "PS"
    echo "PS"
    echo ""
    exit 0
fi


BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
BATTERY_TTL=$(echo "$(acpi -b)" | grep -o '[0-9][0-9]:[0-9][0-9]:[0-9][0-9]')

URGENT_VALUE=20

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "${BATTERY_POWER}%+"
  echo "${BATTERY_POWER}%+"
  echo ""
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  echo "${BATTERY_POWER}%- ${BATTERY_TTL}"
  echo "${BATTERY_POWER}%- ${BATTERY_TTL}"
  echo ""
else
  echo "${BATTERY_POWER}%"
  echo "${BATTERY_POWER}%"
  echo ""
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
