#!/bin/sh

VPNC_FILE='/var/run/vpnc.pid'
OVPN_FILE='/proc/sys/net/ipv4/conf/tun0'

if [[ -e "${VPNC_FILE}" || -e "${OVPN_FILE}" ]]; then
    echo "VPN: on"
    echo "VPN: on"
    echo ""
else
    echo "VPN: off"
    echo "VPN: off"
    echo ""
fi

